//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hqub.GlobalSat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hqub.GlobalSat.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получаем gps-записи (Get Gps Records).
        /// </summary>
        public static string GetGpsRecs {
            get {
                return ResourceManager.GetString("GetGpsRecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получаем заголовки файлов (Get header).
        /// </summary>
        public static string GetHeader {
            get {
                return ResourceManager.GetString("GetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id устройства: {0}.
        /// </summary>
        public static string GetId {
            get {
                return ResourceManager.GetString("GetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт уже открыт..
        /// </summary>
        public static string PORT_ALREADY_OPEN {
            get {
                return ResourceManager.GetString("PORT_ALREADY_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт {0} занят другой программой..
        /// </summary>
        public static string PORT_BLOCKED {
            get {
                return ResourceManager.GetString("PORT_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порт {0} успешно открыт..
        /// </summary>
        public static string PORT_OPENED_SUCCESSFULLY {
            get {
                return ResourceManager.GetString("PORT_OPENED_SUCCESSFULLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track {0} - {1} points.
        /// </summary>
        public static string TRACK_LOADED {
            get {
                return ResourceManager.GetString("TRACK_LOADED", resourceCulture);
            }
        }
    }
}
