//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hqub.GlobalStatDC100.Host {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hqub.GlobalStatDC100.Host.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идет определение COM порта....
        /// </summary>
        public static string AUTO_DETECTION_PORT {
            get {
                return ResourceManager.GetString("AUTO_DETECTION_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистка памяти gps-логгера..
        /// </summary>
        public static string CAPTION_CLEAR_DEVICE {
            get {
                return ResourceManager.GetString("CAPTION_CLEAR_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идет очистка памяти....
        /// </summary>
        public static string CLEAR_MEMORY {
            get {
                return ResourceManager.GetString("CLEAR_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл конфигурации не найден..
        /// </summary>
        public static string CONFIG_NOT_FOUND {
            get {
                return ResourceManager.GetString("CONFIG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идет установка соединения с сервером....
        /// </summary>
        public static string CONNECT_TO_SERVER {
            get {
                return ResourceManager.GetString("CONNECT_TO_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход из программы.
        /// </summary>
        public static string EXIT_FROM_APP_CAPTION {
            get {
                return ResourceManager.GetString("EXIT_FROM_APP_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы увереные что хотите завершить работу программы?.
        /// </summary>
        public static string EXIT_FROM_APP_QUESTION {
            get {
                return ResourceManager.GetString("EXIT_FROM_APP_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выгрузка данных завершена..
        /// </summary>
        public static string EXPORT_DATA_COMPLEATED {
            get {
                return ResourceManager.GetString("EXPORT_DATA_COMPLEATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идет выгрузка данных....
        /// </summary>
        public static string EXPORT_DATA_PROCEED {
            get {
                return ResourceManager.GetString("EXPORT_DATA_PROCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла критическая ошибка
        ///. Перезапустите программу..
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменения сохранены..
        /// </summary>
        public static string GHANGES_SAVED {
            get {
                return ResourceManager.GetString("GHANGES_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Id-устройства не может быть пустым..
        /// </summary>
        public static string ID_DEVICE_EMPTY {
            get {
                return ResourceManager.GetString("ID_DEVICE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружаем лог на сервер ....
        /// </summary>
        public static string LoadLogFileToServer {
            get {
                return ResourceManager.GetString("LoadLogFileToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml files|*.xml|Gpx files|*.gpx|All files|*.*.
        /// </summary>
        public static string OPEN_GPX_DIALOG_FILTER {
            get {
                return ResourceManager.GetString("OPEN_GPX_DIALOG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не может быть пустым..
        /// </summary>
        public static string PASSWORD_IS_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить все записи из устройства?.
        /// </summary>
        public static string QUESTION_CLEAR_DEVICE {
            get {
                return ResourceManager.GetString("QUESTION_CLEAR_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово..
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
    }
}
